version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-ges
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notificacion_ges
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3308:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  cielconcepttogesapi:
    build:
      context: ./
      dockerfile: Dockerfile-cieltoges
    ports:
      - "9091:9091"
    restart: "always"

  apidaemon:
    build:
      context: ./
      dockerfile: Dockerfile-daemon
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: localhost  
      MYSQL_PORT: 3308      
      MYSQL_DATABASE: notificacion_ges 
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      FLASK_PASSWORD: flask_password  # Cambia esto por la contraseña que desees para acceder a la tabla
      restart: "always"
